### ISSUE TITLE
EasyPlayer's restriction system overlaps with Source.Python's built-in one

### ISSUE THREAD

**Issue by Mahi** [MarkusMeskanen/EasyPlayer#6]
Since Source.Python developers added [a built-in restriction system](http://forums.sourcepython.com/viewtopic.php?f=5&t=1120), `EasyPlayer`'s restriction system has become quite redundant. The question left to ask is whether `EasyPlayer` should adapt and change the restriction system to internally use the Source.Python's restriction system, or if it should be completely gotten rid of.

At least two reasons to keep `EasyPlayer`'s system (and change it to use SP internally):
- It's quite unarguably easier to do `player.restrictions += {'weapon_awp'}` than it is to use SP's system, especially if you're just doing something quick and easy. WC:GO is currently the largest project I'm aware of that uses `EasyPlayer`, and adding restrictions this way in heroes is much simpler.
- Backwards compability. This isn't such huge issue, since `EasyPlayer` isn't widely used in any large projects. But it surely isn't a bad thing to have.

And two reasons to get rid of it:
- "There should be one-- and preferably only one --obvious way to do it."
- While Source.Python's system doesn't allow the utilization of Python's powerful `set`s`, it has team restrictions which seem rather hard to add to`EasyPlayer`'s system with individual`set`s for each player.

Any opinions? @satoon101 @Ayuto @Predz @KirillMysnik (if any of you guys are still interested in `EasyPlayer`)

**Comment by satoon101** [comment]
One could also easily use:

``` python
player.restrict_weapons('weapon_one', 'weapon_two')
player.restrict_weapons('weapon_three')

player.unrestrict_weapons('weapon_two')
```

The tricky part with that is if two plugins restrict the same weapon and one un-restricts.  The other will still be expecting the weapon to be restricted.  That is why we recommend using a separate restriction handler per plugin/sub-plugin.

**Comment by Mahi** [comment]
As you mentioned, it causes issues when two plugins collide, which is the exact opposite of what `EasyPlayer` tries to do. However, you made me realize that the current `EasyPlayer`'s system also runs into the exact same problem, so maybe using separate handlers would be better in general... I'm considering removing the `EasyPlayer`'s system completely.

**Edit:** Also, didn't do my research well enough, I didn't even know you had added `restrict_weapons` and `unrestrict_weapons` methods.

**Comment by Mahi** [comment]
I've removed the restriction system from `EasyPlayer`: https://github.com/Mahi/EasyPlayer/commit/c39056b538859d2f2fe120ef1421c8c3961ffca1

As of now, one shall use Source.Python's restriction system.
