### ISSUE TITLE
AttributeError: module 'easyplayer' has no attribute 'EasyPlayer' 

### ISSUE THREAD

**Issue by Hetachi** [MarkusMeskanen/EasyPlayer#7]
I have this problem

AttributeError: module 'easyplayer' has no attribute 'EasyPlayer' 

Can't figure out what's wrong.

**Comment by Mahi** [comment]
[EasyPlayer has been updated to version 2.0](https://github.com/Mahi/EasyPlayer/releases/tag/v2.0.0), which renamed the player class to just `Player`. If you have existing code which uses an older version, it's highly recommended that you update it to match the latest EasyPlayer version. Don't worry, a huge update like this won't happen again, at least in the foreseeable future.

If upgrading your code is not an option, the easiest way to get everything to work again is to import the `Player` class as `EasyPlayer`:

```
from easyplayer import Player as EasyPlayer
```

And it is still possible to use the old EasyPlayer by downloading [the version 1.4](https://github.com/Mahi/EasyPlayer/releases/tag/v2.0.0), although it's highly recommended not to do this, as that version is no longer being maintained or developed.

Don't be afraid to ask if any further questions occur, porting to 2.0 might need a few changes.

**Comment by Hetachi** [comment]
I am writing because I was unable to launch wcs, I guess I will try to update that code to fix this issue.

**Comment by Mahi** [comment]
I suppose you mean [WC:GO](https://github.com/Warcraft-GO-Team/Warcraft-GO), and yes, it hasn't been updated yet. If you manage to update it, feel free to do a pull request.
