### ISSUE TITLE
Where is the addons folder?

### ISSUE THREAD

**Issue by jordanbriere** [MarkusMeskanen/EasyPlayer#8]
I'm kind of a noob, trying to setup an RPG server and [installation](https://github.com/Mahi/EasyPlayer/blob/master/README.md#how-to-install-and-use) says to extract the addons folder into my game directory but I didn't find it... what am I doing wrong?

Obviously I'm kidding here but yeah, the package structure is not right for an easy-install. :stuck_out_tongue_winking_eye:

**Comment by Mahi** [comment]
Thanks for the report and sorry for the delayed answer, I must've missed this issue.

Anyways, the addons folder is already properly provided in the release .zip files: https://github.com/Mahi/EasyPlayer/releases and in fact the installation instructions [clearly state to download it from the releases page](https://github.com/Mahi/EasyPlayer#how-to-install-and-use).

The addons folder is not a necessary part of the source code but only related to installation, thus it's not included in the repository but in the releases.

**Comment by jordanbriere** [comment]
Alright, makes sense. Just assumed that, since it doesn't requires any binaries to be compiled, the main clone/download button would reflect the right structure.

**Comment by Mahi** [comment]
Well it technically does reflect the right structure, the root folder just isn't your game directory but `../addons/source-python/packages/custom` directory. It just doesn't match the installation instructions (which tell you to use releases page).

Anyways, thanks for the feedback, I will give it a further thought.
